In [1]:
# Basic imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Get data from keras datasets
from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 2s 0us/step


In [3]:
# Check shape of datasets

# Train
print('X train shape: ', x_train.shape)
print('Y train shape: ', y_train.shape)

# Test
print('X test shape: ', x_test.shape)
print('Y test shape: ', y_test.shape)

X train shape:  (60000, 28, 28)
Y train shape:  (60000,)
X test shape:  (10000, 28, 28)
Y test shape:  (10000,)


In [4]:
# Reshape channels to data

x_train = x_train.reshape(-1,28,28,1)
y_train = y_train.reshape(-1,1)

# Reshape y to categorical
from keras.utils.np_utils import to_categorical
y_train = to_categorical(y_train, num_classes=10)

print('X train shape: ', x_train.shape)
print('Y train shape: ', y_train.shape)

X train shape:  (60000, 28, 28, 1)
Y train shape:  (60000, 10)


In [5]:
# Import layers
from keras import backend as K

# Set to train phase and set that channels are last (=tensorflow backend)
K.set_learning_phase(1)
K.set_image_data_format('channels_last')

# GPU settings
if 'tensorflow' == K.backend():
    import tensorflow as tf
    from keras.backend.tensorflow_backend import set_session
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    config.gpu_options.allocator_type = 'BFC'
    config.gpu_options.visible_device_list = "0"
    set_session(tf.Session(config=config))

In [6]:
# Import layers etc
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.convolutional import Convolution2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization

from keras import optimizers

In [7]:
# Define model

model = Sequential()

model.add(Convolution2D(input_shape=(28,28,1), filters=4, kernel_size=5, strides=1))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Convolution2D(filters=8, kernel_size=3, strides=1))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Convolution2D(filters=16, kernel_size=3, strides=1))
model.add(BatchNormalization())
model.add(Activation('relu'))

model.add(Convolution2D(filters=16, kernel_size=3, strides=1))
model.add(BatchNormalization())
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(1,1)))

model.add(Flatten())
model.add(Dense(6*6*16, kernel_initializer='normal'))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(256, kernel_initializer='normal'))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(128, kernel_initializer='normal'))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(10, kernel_initializer='normal'))
model.add(Activation('softmax'))

adam = optimizers.Adam(lr=0.05, decay=0.01)

model.compile(loss = 'categorical_crossentropy', optimizer = adam)

In [8]:
# Fit

from keras.callbacks import EarlyStopping

cb = [EarlyStopping(monitor='val_loss', min_delta=1e-06, patience=10)]

model.fit(x_train, y_train, epochs=300, batch_size=32, validation_split=0.1, callbacks=cb)

Train on 54000 samples, validate on 6000 samples
Epoch 1/300
54000/54000 [==============================] - 17s 311us/step - loss: 1.4876 - val_loss: 1.2525
Epoch 2/300
54000/54000 [==============================] - 15s 270us/step - loss: 1.2523 - val_loss: 1.1248
Epoch 3/300
54000/54000 [==============================] - 15s 269us/step - loss: 1.0425 - val_loss: 0.9161
Epoch 4/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.8908 - val_loss: 0.7843
Epoch 5/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.8114 - val_loss: 0.7357
Epoch 6/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.7628 - val_loss: 0.6946
Epoch 7/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.7225 - val_loss: 0.6753
Epoch 8/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.7106 - val_loss: 0.6476
Epoch 9/300
54000/54000 [==============================] - 15s 272us/step - loss: 0.685

Epoch 76/300
54000/54000 [==============================] - 14s 268us/step - loss: 0.3561 - val_loss: 0.3333
Epoch 77/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.3630 - val_loss: 0.3342
Epoch 78/300
54000/54000 [==============================] - 14s 268us/step - loss: 0.3568 - val_loss: 0.3356
Epoch 79/300
54000/54000 [==============================] - 14s 268us/step - loss: 0.3479 - val_loss: 0.3325
Epoch 80/300
54000/54000 [==============================] - 14s 268us/step - loss: 0.3499 - val_loss: 0.3338
Epoch 81/300
54000/54000 [==============================] - 14s 268us/step - loss: 0.3506 - val_loss: 0.3358
Epoch 82/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.3487 - val_loss: 0.3245
Epoch 83/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.3484 - val_loss: 0.3242
Epoch 84/300
54000/54000 [==============================] - 14s 268us/step - loss: 0.3481 - val_loss: 0.3343
Epoch 85/300
54000/

54000/54000 [==============================] - 14s 268us/step - loss: 0.2814 - val_loss: 0.2480
Epoch 151/300
54000/54000 [==============================] - 14s 268us/step - loss: 0.2745 - val_loss: 0.2418
Epoch 152/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.2744 - val_loss: 0.2439
Epoch 153/300
54000/54000 [==============================] - 15s 269us/step - loss: 0.2745 - val_loss: 0.2541


In [10]:
from keras.models import load_model

# Save model
#model.save('C:/Users/Daniel/MNIST/mnist_cnn_first.h5')

# Load model

model = load_model('C:/Users/Daniel/MNIST/mnist_cnn_first.h5')

In [11]:
# Reshape channels to data

x_test = x_test.reshape(-1,28,28,1)
y_test = y_test.reshape(-1,1)

# Reshape y to categorical
y_test = to_categorical(y_test, num_classes=10)

print('X test shape: ', x_test.shape)
print('Y test shape: ', y_test.shape)

X test shape:  (10000, 28, 28, 1)
Y test shape:  (10000, 10)


In [13]:
# Out-sample predictions NN Model

y_test_hat = model.predict(x_test).astype('float64')

In [111]:
# binary predictions
y_hat_bin = (y_test_hat == y_test_hat.max(axis=1)[:,None]).astype(int)

In [175]:
# Accuracy metrics
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

conf_mat = []
for i in range(0,y_test.shape[1]):
    conf_mat.append(confusion_matrix(y_test[:,i],y_hat_bin[:,i]))
conf_mat = np.array(conf_mat)
    
print(accuracy_score(y_test, y_hat_bin))
print(f1_score(y_test, y_hat_bin, average='weighted'))
print(conf_mat)

0.9304
0.93093873835
[[[8991   29]
  [  32  948]]

 [[8844   21]
  [  32 1103]]

 [[8865  103]
  [  71  961]]

 [[8916   74]
  [  87  923]]

 [[8978   40]
  [  40  942]]

 [[9027   81]
  [ 108  784]]

 [[9022   20]
  [  44  914]]

 [[8941   31]
  [  86  942]]

 [[8810  216]
  [ 106  868]]

 [[8910   81]
  [  90  919]]]
